#!/bin/bash
# cstg++: g++ compile with option tags for c++ course, then run
# author: Wonho Lim

#   ARG1: Output file name
#   ARG2: Source file name

clear && g++ -pedantic -Wall -Wextra -W -g -std=c++0x -o $1 $2 && ./$1
