#!/bin/bash
# csts: BCIT sftp access script - default CST (COMP)
# author: Wonho Lim
# version: 1.1

#   $1: c, i or o ("Home Drive/MyCourses", share-in or share-out)
#   $2: course number

PROGRAM_TAG="COMP"
SERVER_ADDRESS="files.bcit.ca"
STUDENT_NO="A00827033"

FLAG="error"

case ${1} in
    c ) FLAG="Home Drive/MyCourses" ;;
    i ) FLAG="Share In"             ;;
    o ) FLAG="Share Out"            ;;
esac

if [ "$OPTION" != "error" ]; then
    IPATH=${STUDENT_NO}@${SERVER_ADDRESS}:"$FLAG"/${PROGRAM_TAG}
    case ${1} in
    c ) sftp "$IPATH${2}"   ;;
    * ) sftp "$IPATH/${2}"  ;;
    esac
fi
